# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib rsmith
read_file <- function(path) {
    .Call('rsmith_read_file', PACKAGE = 'rsmith', path)
}

